site_name: Code Secure
site_url: https://0xdu.github.io/swagger-xss/
site_author: Duo
site_description: >-
  Code Secure
repo_name: Code Secure
repo_url: https://github.com/0xdu/swagger-xss
edit_uri: "blob/main/docs/"
copyright: Copyright &copy; 2024 Duo

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.footer
  - content.action.edit
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  highlightjs: true
  hljs_languages:
  - yaml
  font:
    text: Inter
nav:
- Home: index.md
- Getting Started:
  - Installation: installation.md
  - Setting:
    - Notification: setting/notification.md
    - Authentication: setting/authentication.md
    - CI Access Token: setting/ci-token.md
  - Security Integration:
    - scanner/index.md
    - Static Application Security Testing (SAST):
      - Semgrep: scanner/sast/semgrep.md
      - Gitleaks: scanner/sast/gitleaks.md
    - Software Composition Analysis (SCA):
      - Trivy: scanner/sca/trivy.md