site_name: Code Secure
site_url: https://0xdu.github.io/swagger-xss/
site_author: Duo
site_description: >-
  Code Secure
repo_name: Code Secure
repo_url: https://github.com/0xdu/swagger-xss
edit_uri: "blob/main/docs/"
copyright: Copyright &copy; 2024 Duo

theme:
  name: material
  highlightjs: true
  hljs_languages:
  - yaml

nav:
- Home: index.md
- Getting Started:
  - Installation: installation.md
  - Setting:
    - Notification: setting/notification.md
    - CI Token: setting/ci-token.md
  - Scanner:
    - SAST: scanner/sast.md
    - SCA: scanner/sca.md
    - Secret Detection: scanner/secret_detection.md
