name: Deploy the documentation
on:
  push:
    paths:
    - 'docs/**'
    - mkdocs.yml
    branches:
    - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python runtime
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
        pip install -r docs/build/requirements.txt

    - name: Build documentation
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        mkdocs build --clean
        mkdocs --version

    - name: Adjust permissions
      run: |
        chmod -c -R +rX site/ | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
